### PR TITLE
Interface for visualising process graphs

### PR DESCRIPTION
**Pull request by Ardweaden**

### CODE REVIEW

**Review by m-mohr — CHANGES_REQUESTED** [review]
I don't think this is really the right approach. The request should go through the API for secondary web services. It would need work in the aggregator though. Let's better discuss this at one of the openEO Platform dev telcos.

**Comment by Ardweaden** [comment]
> I don't think this is really the right approach. The request should go through the API for secondary web services. It would need work in the aggregator though. Let's better discuss this at one of the openEO Platform dev telcos.

@m-mohr Just to clarify, this is intended for the "process graph preview" functionality that was discussed a while ago. Would you be so kind to give a brief overview of the expected approach?

**Comment by m-mohr** [comment]
I think the expected approach would be that it uses the openEO API functionality foreseen for this type of data processing, which is the "secondary web services". It seems you do that, but you don't use the corresponding functionality in the web editor. Also, it should go through the aggregator as opening a second connection is undesirable and looks like a dirty workaround. Authentication also wouldn't work so you can't protect against unintended usage from externals.

**Comment by Ardweaden** [comment]
@m-mohr  Thank you! 

I would just say that this functionality is only supposed to be used with SH backend, so if we wanted to use the aggregator, I assume the SH should be made a proper backend. That's why this concept was made in this way.

> I think the expected approach would be that it uses the openEO API functionality foreseen for this type of data processing, which is the "secondary web services". It seems you do that, but you don't use the corresponding functionality in the web editor.

Admittedly I don't quite understand this, the point of this functionality is supposed to be that the user can visualise the graph, or a part of a graph, without creating a secondary service manually. Instead, this functionality creates a service on SH backend automatically.

**Comment by m-mohr** [comment]
> So if we wanted to use the aggregator, I assume the SH should be made a proper backend.

I assume I agree, although we may have different understandings of what a "proper" backend is.

> Admittedly I don't quite understand this, the point of this functionality is supposed to be that the user can visualise the graph, or a part of a graph, without creating a secondary service manually.

Yes, this is a totally fine use case. That is a pure client-side issue though and it's fine to request a better/easier workflow for secondary web services in the Web Editor, but that shouldn't include connecting to a completely different back-end with all its caveats. We could surely figure out a similar behavior that goes through secondary web services and the aggregator.

> Instead, this functionality creates a service on SH backend automatically.

The client is connected to openEO Platform and should create a service there automatically. Why does a client need to bother about the implementation details and that it is hosted on SH? If you go through the aggregator all clients (that implement secondary web services) can be used to visualize process graphs. In the current state, only the Web Editor can handle it due to some proprietary code.

With the current proposal, how do you authenticate?
I think we should discuss this on Wednesday (dev telco).

**Comment by Ardweaden** [comment]
@m-mohr 
Thanks, I just wanted to clarify the issues so I understand them. (I am not writing these comments as arguments for why the implementation should stay as it is).

I completely agree doing this on the level of the aggregator would be preferable.

> The client is connected to openEO Platform and should create a service there automatically. Why does a client need to bother about the implementation details and that it is hosted on SH? If you go through the aggregator all clients (that implement secondary web services) can be used to visualize process graphs. In the current state, only the Web Editor can handle it due to some proprietary code.

Yes, of course. I considered that because the SH backend isn't (yet) used in the aggregator, the most straightforward solution was just to have a separate connection to the "visualizing" backend.
Of course, the idea was specifically to use SH with the library that converts process graphs to evalscripts for this functionality, as it would be (supposedly) faster, and would allow visualising partial process graphs etc. So the aggregator should always delegate this to SH, but I digress.

> With the current proposal, how do you authenticate?

Well, in the initial concept we decided to use unauthenticated SH WMTS service.

**Pull request closed without merging**
